### PR TITLE
Fix: Combobox not opening on focus

### LINKED ISSUE #1173: Add Time & Add time off Modal: Clicking dropdown body isn't opening dropdown, only works on chevron
Steps to Reproduce:

1. Open "Add Time" modal or "Add time off" modal
2. Click directly on the body area (not the chevron ▼) of the Project or Task dropdown
3. Actual: Dropdown list does not opens

### Expected:
Dropdown does not open on click on the field body. It only works on typing and chevron. User experience could be enhanced if we enable dropdown listing on click on entire field.

### PR DESCRIPTION
**Pull request by b1ink0**
## Description

This PR fixes Combobox not opening on focus across codebase.

## Screenshot/Screencast

https://github.com/user-attachments/assets/0c6a3f2c-d13c-4455-abef-97ea538c057b

## Checklist

- [x] I have carefully reviewed the code before submitting it for review.
- [ ] This code is adequately covered by unit tests to validate its functionality.
- [x] I have conducted thorough testing to ensure it functions as intended.
- [ ] A member of the QA team has reviewed and tested this PR (To be checked by QA or code reviewer)

Fixes #1173

### CODE REVIEW

**Review by PraveenKum11 — APPROVED** [review]
LGTM

File: frontend/packages/app/src/pages/timesheet/personal/reducer.ts [hunk 1]
```diff
@@ -57,6 +57,10 @@ export function timesheetReducer(
 ): TimesheetState {
   switch (action.type) {
     case "SEARCH_CHANGED":
+      if (state.filters.search === action.payload) {
+        return state;
+      }
+
```
Comment (b1ink0) [inline frontend/packages/app/src/pages/timesheet/personal/reducer.ts:63]: Fixes issue where switching form team to personal timesheet cause infinite scroll to break on the personal timesheet.
