### PR TITLE
Bug-Fix: Submission failure when applying for leaves

### LINKED ISSUE #1159: Bug: MandatoryError in Next PMS Leave Application
# 🐛 Bug Report

## **Description**
Error Log : 
```
{
    "exception": "frappe.exceptions.MandatoryError: [Leave Application, HR-LAP-2026-00001]: description",
    "exc_type": "MandatoryError",
    "exc": "[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 121, in application\\n    response = frappe.api.handle(request)\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 63, in handle\\n    data = endpoint(**arguments)\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 46, in create_doc\\n    return frappe.new_doc(doctype, **data).insert()\\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 448, in insert\\n    self._validate()\\n    ~~~~~~~~~~~~~~^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 785, in _validate\\n    self._validate_mandatory()\\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 1126, in _validate_mandatory\\n    raise frappe.MandatoryError(\\n    ...<3 lines>...\\n    )\\nfrappe.exceptions.MandatoryError: [Leave Application, HR-LAP-2026-00001]: description\\n\"]",
    "_server_messages": "[\"{\\\"message\\\":\\\"Error: Value missing for Leave Application: Reason\\\",\\\"as_table\\\":false,\\\"title\\\":\\\"Message\\\"}\"]"
}
```

## **Steps to Reproduce**
1. Go to [stage](https://erp-stage.rt.gw/next-pms/timesheet) 
2. Click on `Add Time-Off` button 
3. fill the necessary details 
4. click on `Add Time-Off` button  

## **Expected Behavior**
- leave application gets submitted 

## **Actual Behavior**
- got error saying `frappe.exceptions.MandatoryError` 

## **Screenshots/Screencasts**

https://github.com/user-attachments/assets/805b093f-d193-4f55-a916-487e608ad521

## **Environment**
- OS: [e.g., Windows 10, macOS 13]
- Browser: [e.g., Chrome 109, Firefox 90]

## **Additional Context**
[Add any other context about the problem here.]

### PR DESCRIPTION
**Pull request by ayushnirwal**
## Description

- Fixes errors in submitting time off due to bad payload
- Fixes race condition in pulling dev context data causing add leave button to disappear intermittently.

## Checklist

- [x] I have carefully reviewed the code before submitting it for review.
- [ ] This code is adequately covered by unit tests to validate its functionality.
- [x] I have conducted thorough testing to ensure it functions as intended.
- [ ] A member of the QA team has reviewed and tested this PR (To be checked by QA or code reviewer)

Fixes #1159

### CODE REVIEW

File: frontend/packages/app/src/pages/timesheet/components/add-leave/index.tsx [hunk 1]
```diff
@@ -67,12 +70,13 @@ const AddLeave = ({ open = false, onOpenChange }: LeaveTimeProps) => {
...
-        value.leaveType === "first-half" || value.leaveType === "second-half";
+        value.leaveDuration === "first-half" ||
+        value.leaveDuration === "second-half";
 
       try {
         const data = {
           employee: employeeId,
-          description: "",
+          description: value.reason,
           from_date: value.fromDate,
```
Comment (b1ink0) [inline frontend/packages/app/src/pages/timesheet/components/add-leave/index.tsx:86]: For field `custom_first_halfsecond_half`, for a full day, there is a need to pass an empty string otherwise, it throws an error on staging. However, passing "Full Day" works on the local setup.

```lua

{
    "exception": "frappe.exceptions.ValidationError:  First Half/Second Half cannot be \"Full Day\". It should be one of \"\", \"First Half\", \"Second Half\"",
    "exc_type": "ValidationError",
    "exc": "[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 121, in application\\n    response = frappe.api.handle(request)\\n  File \\\"apps/frappe/frappe/api/__init__.py\\\", line 63, in handle\\n    data = endpoint(**arguments)\\n  File \\\"apps/frappe/frappe/api/v1.py\\\", line 46, in create_doc\\n    return frappe.new_doc(doctype, **data).insert()\\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 448, in insert\\n    self._validate()\\n    ~~~~~~~~~~~~~~^^\\n  File \\\"apps/frappe/frappe/model/document.py\\\", line 787, in _validate\\n    self._validate_selects()\\n    ~~~~~~~~~~~~~~~~~~~~~~^^\\n  File \\\"apps/frappe/frappe/model/base_document.py\\\", line 1114, in _validate_selects\\n    frappe.throw(\\n    ~~~~~~~~~~~~^\\n    \\t_('{0} {1} cannot be \\\"{2}\\\". It should be one of \\\"{3}\\\"').format(\\n     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n    \\t\\tprefix, label, value, comma_options\\n      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n    \\t)\\n     ^\\n    )\\n    ^\\n  File \\\"apps/frappe/frappe/utils/messages.py\\\", line 159, in throw\\n    msgprint(\\n    ~~~~~~~~^\\n    \\tmsg,\\n     ^^^^\\n    ...<7 lines>...\\n    \\tallow_dangerous_html=allow_dangerous_html,\\n     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n    )\\n    ^\\n  File \\\"apps/frappe/frappe/utils/messages.py\\\", line 118, in msgprint\\n    _raise_exception()\\n    ~~~~~~~~~~~~~~~~^^\\n  File \\\"apps/frappe/frappe/utils/messages.py\\\", line 59, in _raise_exception\\n    raise exc\\nfrappe.exceptions.ValidationError:  First Half/Second Half cannot be \\\"Full Day\\\". It should be one of \\\"\\\", \\\"First Half\\\", \\\"Second Half\\\"\\n\"]",
    "_server_messages": "[\"{\\\"message\\\":\\\" First Half/Second Half cannot be \\\\\\\"Full Day\\\\\\\". It should be one of \\\\\\\"\\\\\\\", \\\\\\\"First Half\\\\\\\", \\\\\\\"Second Half\\\\\\\"\\\",\\\"as_table\\\":false,\\\"title\\\":\\\"Message\\\",\\\"indicator\\\":\\\"red\\\",\\\"raise_exception\\\":1,\\\"__frappe_exc_id\\\":\\\"a906adbd337703cf43ee1659714b99s1ab4d32d62a9c25e346d8ec057\\\"}\"]"
}
```

@wreckage0907 please take a look ^

Comment (wreckage0907) [reply frontend/packages/app/src/pages/timesheet/components/add-leave/index.tsx:86]: @b1ink0 please note : 
1. field `custom_first_halfsecond_half` should be empty for full day . https://github.com/rtCamp/next-pms/blob/65427bb3bfca5efb0234e24ffcee092ee487d107/frontend/packages/app/src/pages/timesheet/components/add-leave/index.tsx#L67-L70 needs to be addressed 
2. description should be value.reason like how the PR has addressed it , its a mandatory field

Comment (b1ink0) [reply frontend/packages/app/src/pages/timesheet/components/add-leave/index.tsx:86]: @ayushnirwal ^

**Review by b1ink0 — APPROVED** [review]
