### PR TITLE
Fix: Editing time entries. 

### LINKED ISSUE #916: Editing timesheet from ERP results in QL Editor output
# 🐛 Bug Report

## **Description**
When we edit or add a timesheet description from the ERP backend, the saved HTML gets automatically wrapped in QL Editor divs and classes - this breaks the output for multiple components.

## **Steps to Reproduce**
1. From ERP backend, Go to http://next-pms.localhost/desk/timesheet
2. Edit an existing timesheet or add a new one
3. Add all the required details
4. Save the timesheet
5. Now go to personal timesheet and check the timesheet, it will be wrapped in ql editor html

## **Expected Behavior**
The output should not be wrapped in QL editor classes

## **Actual Behavior**
The output is wrapped in QL editor classes

## **Screenshots/Screencasts**

Image

Image

Image

### PR DESCRIPTION
**Pull request by ayushnirwal**
## Description

- Use TextEditor from `frappe-ui-react` instead of textarea.

## Screenshot/Screencast

Screenshot 2026-04-06 at 7 33 07 PM

Screenshot 2026-04-06 at 7 32 39 PM
Screenshot 2026-04-06 at 8 33 26 PM

## Checklist

- [x] I have carefully reviewed the code before submitting it for review.
- [ ] This code is adequately covered by unit tests to validate its functionality.
- [x] I have conducted thorough testing to ensure it functions as intended.
- [ ] A member of the QA team has reviewed and tested this PR (To be checked by QA or code reviewer)

Fixes #916

### CODE REVIEW

File: frontend/packages/app/src/components/timesheet-row/components/inline-time-entry/index.tsx
Comment (b1ink0) [inline frontend/packages/app/src/components/timesheet-row/components/inline-time-entry/index.tsx:329]: This is shown when the time entry is minimized. I think we should strip any HTML from the description and display only plain text here.

We can add a simple stripTags utility function I think.

https://github.com/user-attachments/assets/34ac4c91-e26e-4a75-956f-5b5bec4c77b5

File: frontend/packages/app/src/pages/timesheet/team/weekly-approval/entryRow.tsx [hunk 1]
```diff
@@ -69,12 +69,12 @@ const EntryRow = ({ entry, onSave }: EntryRowProps) => {
...
-              onChange={(e) => setDescription(e.target.value)}
-              placeholder="Enter description"
-              className="bg-white border-outline-gray-2"
-              rows={2}
+            <TextEditor
+              content={description}
+              onChange={(val) => setDescription(val)}
+              fixedMenu={false}
+              placeholder="Comment"
+              editorClass="h-24 overflow-scroll bg-white border rounded-md border-outline-gray-2"
```
Comment (b1ink0) [inline frontend/packages/app/src/pages/timesheet/team/weekly-approval/entryRow.tsx]: Wherever `overflow-scroll` is used, replace it with `overflow-auto` so the scrollbar is only visible when the content exceeds the container height. At the same time, add `scrollbar` or `scrollbar-thin` classes to maintain consistent scrollbar styling across the application.

File: frontend/packages/app/src/pages/timesheet/components/add-time/index.tsx [hunk 2]
```diff
@@ -266,10 +266,11 @@ const AddTime = ({
...
                 <label className="block text-xs text-ink-gray-5">Comment</label>
-                <Textarea
-                  value={field.state.value}
-                  onChange={(e) => field.handleChange(e.target.value)}
-                  className="bg-white border-outline-gray-2"
+                <TextEditor
+                  content={field.state.value}
+                  onChange={(value) => field.handleChange(value)}
+                  fixedMenu={false}
+                  editorClass="h-24 overflow-scroll bg-white border rounded-md border-outline-gray-2"
```
Comment (b1ink0) [inline frontend/packages/app/src/pages/timesheet/components/add-time/index.tsx]: See: https://github.com/rtCamp/next-pms/pull/1178/changes#r3043949415

Comment (b1ink0) [inline frontend/packages/app/src/pages/timesheet/components/add-time/index.tsx]: Add `px-2` padding to the TextEditor when in edit mode so the text is not close to the container border.

Current:
Image

With Padding:
Image

Comment (b1ink0) [reply frontend/packages/app/src/pages/timesheet/components/add-time/index.tsx]: Apply everywhere where TextEditor component is used with edit mode.

**Review by b1ink0 — CHANGES_REQUESTED** [review]

File: frontend/packages/app/src/pages/timesheet/team/weekly-approval/entryRow.tsx (hunk 1 above)
Comment (b1ink0) [reply frontend/packages/app/src/pages/timesheet/team/weekly-approval/entryRow.tsx]: Current:

Screenshot 2026-04-07 at 2 45 17 PM

With `overflow-auto`:

Screenshot 2026-04-07 at 2 46 05 PM

**Review by PraveenKum11 — APPROVED** [review]
Code LGTM

@ayushnirwal I am seeing some issues with the TextEditor itself but I suppose that will be a separate PR.

Image

**Review by b1ink0 — APPROVED** [review]
LGTM
